### ISSUE TITLE
Cannot get to start: DNS error

### ISSUE THREAD

**Issue by Kamshak** [AzureADSamples/WebAPI-Nodejs#12]
To run the application it says to run  
$ cd node-server
$ node server.js

In my node-server folder there is no server.js. Only a file called app.js. When running it i get this error:

c9@appdev:~/WebAPI-Nodejs/node-server$ node app.js | bunyan
[2015-06-15T07:58:55.971Z]  INFO: Windows Azure Active Directory Sample/1927 on appdev: MongoDB Schema loaded
[2015-06-15T07:58:56.051Z]  INFO: Microsoft OpenID Connect: Passport Strategy/1927 on appdev: Audience provided to Strategy was:  http://<mserver's IP>:8888/
[2015-06-15T07:58:56.053Z]  INFO: Microsoft OpenID Connect: Passport Strategy/1927 on appdev: Metadata url provided to Strategy was:  https://login.microsoftonline.com/hypercubeb2c.onmicrosoft.com/.well-known/openid-configuration?p=b2c_1_B2CSI/
[2015-06-15T07:58:56.054Z]  INFO: Microsoft OpenID Connect: Passport Strategy/1927 on appdev: Req: undefined

/home/c9/WebAPI-Nodejs/node-server/node_modules/mongoose/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

**Comment by brandwe** [comment]
you must have MongoDB installed as the instructions state.

**Comment by Kamshak** [comment]
Thanks
